version: '3.9'
services:
  engine:
    build:
      context: .
      dockerfile: nobash.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - frontend:/usr/src/spareduck/www
      - ./src:/usr/src/spareduck/src
      - nodemodules:/usr/src/spareduck/www/node_modules
    image: spareduck:latest

volumes:
  frontend: {}
  nodemodules: {}
